// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHwe5RGbpWkSapSw82_bRPeS5CtwNDZA',
    appId: '1:262391776906:android:f289f2d2e5a25b5c004f73',
    messagingSenderId: '262391776906',
    projectId: 'let-s-party-bb4ea',
    databaseURL: 'https://let-s-party-bb4ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'let-s-party-bb4ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTF-Z3aYybrPYkIJ-iUnwY0yvUiS2_iE',
    appId: '1:262391776906:ios:05c1e75fa8c4166c004f73',
    messagingSenderId: '262391776906',
    projectId: 'let-s-party-bb4ea',
    databaseURL: 'https://let-s-party-bb4ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'let-s-party-bb4ea.appspot.com',
    iosClientId: '262391776906-kps34g69dqromf49647m5rt4kirjb7kf.apps.googleusercontent.com',
    iosBundleId: 'tech.hashbear.letsParty',
  );
}
